const tileData = [
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "6",
    "UserName": "Julia",
    "DisplayName": "Me Too! Club Chaperone (Every Tuesday)",
    "Suitabilities": "First Timers, Open to All",
    "volunteerId": 6947172,
    "Title": "Me Too! Club Chaperone (Every Tuesday)",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=6947155",
    "FutureDate": 2,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=6947164",
    "Duration": "Tue, 22 May 2018",
    "Town": "Yishun",
    "VolunteerOrgName": "Me Too! Club (MINDS)",
    "Frequency": "8:30 AM to 12:30 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  },
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "12",
    "UserName": "Jagdish",
    "DisplayName": "NNI CLINIC GREETERS",
    "Suitabilities": "First Timers, Seniors, Open to All",
    "volunteerId": 7084792,
    "Title": "NNI CLINIC GREETERS",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=7107611",
    "FutureDate": 13,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=7084790",
    "Duration": "Tue, 22 May 2018",
    "Town": "Novena",
    "VolunteerOrgName": "National Neuroscience Institute",
    "Frequency": "9:00 AM to 1:00 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  },
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "10",
    "UserName": "Zach",
    "DisplayName": "R.E.A.L (Re-Learn and Enjoy Active Living) Programme",
    "Suitabilities": "Open to All",
    "volunteerId": 4847433,
    "Title": "R.E.A.L (Re-Learn and Enjoy Active Living) Programme",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=7089418",
    "FutureDate": 4,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=3770749",
    "Duration": "Wed, 23 May 2018",
    "Town": "Bukit Merah",
    "VolunteerOrgName": "Stroke Support Station Ltd.",
    "Frequency": "1:30 PM to 4:30 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  },
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "311",
    "UserName": "Mohamad Sharil Abdul Rahim",
    "DisplayName": "Karaoke",
    "Suitabilities": "First Timers, Seniors, Open to All",
    "volunteerId": 4958014,
    "Title": "Karaoke",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=6358546",
    "FutureDate": 31,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=3232312",
    "Duration": "Wed, 23 May 2018",
    "Town": "Ang Mo Kio",
    "VolunteerOrgName": "Ang Mo Kio - Thye Hua Kwan Hospital",
    "Frequency": "2:00 PM to 5:00 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  },
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "0",
    "UserName": "Adrian Si",
    "DisplayName": "MWC Help Kiosk",
    "Suitabilities": "Open to All",
    "volunteerId": 6405838,
    "Title": "MWC Help Kiosk",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=6405828",
    "FutureDate": 1,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=6405834",
    "Duration": "Wed, 23 May 2018",
    "Town": "Paya Lebar",
    "VolunteerOrgName": "Migrant Workers' Centre",
    "Frequency": "7:00 PM to 9:00 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  },
  {
    "hasMore": true,
    "isVolunteer": true,
    "publicAccess": true,
    "Openings": "8",
    "UserName": "Koo Hui Ying",
    "DisplayName": "Craftwork & Maintenance @ Kampung Kampus (May to Jul 2018)",
    "Suitabilities": "First Timers, Open to All",
    "volunteerId": 7039681,
    "Title": "Craftwork & Maintenance @ Kampung Kampus (May to Jul 2018)",
    "VolunteerUrl": "\/volunteer-event?event_activity_id=7039652",
    "FutureDate": 6,
    "isRegular": false,
    "Url": "\/image\/logo?img_id=7039673",
    "Duration": "Thu, 24 May 2018",
    "Town": "Yishun",
    "VolunteerOrgName": "Ground-Up Initiative (GUI)",
    "Frequency": "10:00 AM to 4:00 PM",
    "ncssOppoId": "isEmptyField",
    "ncssImageUrl": "",
    "ncssRedirectUrl": ""
  }
];

export default tileData;